In [5]:
import numpy as np


In [15]:
# Task-16: How to add a border (filled with 0's) around an existing array?

arr = np.random.randint(1, 9, (6, 6))
print(arr)

arr = np.pad(arr, pad_width=2, mode='constant', constant_values=0)
print(arr)

[[6 2 1 5 6 4]
 [3 2 4 2 5 4]
 [7 8 6 3 2 6]
 [3 1 6 1 6 2]
 [6 1 6 6 2 6]
 [7 8 6 1 5 7]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 6 2 1 5 6 4 0 0]
 [0 0 3 2 4 2 5 4 0 0]
 [0 0 7 8 6 3 2 6 0 0]
 [0 0 3 1 6 1 6 2 0 0]
 [0 0 6 1 6 6 2 6 0 0]
 [0 0 7 8 6 1 5 7 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [7]:
# Task-17: What is the result of the following expression?
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1
# nan = not a number, inf = infinite

print(0 * np.nan) # nan
print(np.nan == np.nan) # False
print(np.inf > np.nan) # False
print(np.nan - np.nan) # nan
print(np.nan in set([np.nan])) # True
print(0.3 == 3 * 0.1) # False


nan
False
False
nan
True
False


In [16]:
# Task-18: Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

a = np.diag(1 + np.arange(4), k = -1) # here for the value of 1-4, we take an 1D array using np.arange(), 
                                      #then k=-1 defines the 1st down diagonal
print(a)

ar = np.diag(np.arange(1, 5), k = -1)
print(ar)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [20]:
# Task-19: Create a 8x8 matrix and fill it with a checkerboard pattern

p = np.zeros((8, 8), dtype = int) # dtype = int, for integer datatype, else default datatype is double
p[::2, ::2] = 1 # starting row and the rows same as the starting row
p[1::2, 1::2] = 1 # the second row and the rows same as the second row
print(p)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [21]:
# Task-20: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(99, (6, 7, 8)))
print(np.unravel_index(99, (6, 7, 8), order = 'C')) # row wise
print(np.unravel_index(99, (6, 7, 8), order = 'F')) # column wise

(1, 5, 3)
(1, 5, 3)
(3, 2, 2)
