In [1]:
# Task-1: Import the numpy package under the name np

import numpy as np

In [5]:
# Task-2: Print the numpy version and the configuration

print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/mursalin/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/mursalin/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/mursalin/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/mursalin/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/mursalin/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/mursalin/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/mursalin/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/mursalin/anaconda3/include']
None


In [7]:
# Task-3: Create a null vector of size 10
# Creating an vector ---> np.array(list_name), when the list is given

null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
# Task-4: How to find the memory size of any array

print(null_vector.size) # size of the array
print(null_vector.itemsize) # memory located for an item
print("%d bytes" % (null_vector.size * null_vector.itemsize))

10
8
80 byte


In [14]:
# Task-5: How to get the documentation of the numpy add function from the command line?
# >>> import numpy as np
# >>> print(np.info(np.add))

print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [15]:
# Task-6: Create a null vector of size 10 but the fifth value which is 1 

nv = np.zeros(10)
nv[4] = 1
print(nv[4])
print(nv)

1.0
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [40]:
# Task-7: Create a vector with values ranging from 10 to 49

n = [i+10 for i in range(40)]
# for i in n[0:40:1]:
#     print(n[i])
vec1 = np.array(n)
print(vec1)

vec2 = np.arange(10, 50)
print(vec2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [49]:
# Task-8: Reverse a vector (first element becomes last)

vec1 = vec1[::-1]
print(vec1)

vec3 = vec1[10:20:2] # only positive value supported ::+ve
print(vec3)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[]


In [53]:
# Task-9: Create a 3x3 matrix with values ranging from 0 to 8

mat1 = np.arange(0, 9)
print(mat1)
mat1 = mat1.reshape(3, 3)
print(mat1)

mat2 = np.arange(0, 9).reshape(3, 3)
print(mat2)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [56]:
# Task-10: Find indices of non-zero elements from [1,2,0,0,4,0]

n = [1, 2, 0, 0, 4, 0]
ar = np.array(n)
print(np.nonzero(ar))

arr = np.nonzero(ar)
print(arr) # returns an array 

(array([0, 1, 4]),)
(array([0, 1, 4]),)


In [60]:
# Task-11:  Create a 3x3 identity matrix

mat3 = np.identity(3)
print(mat3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [73]:
# Task-12: Create a 3x3x3 array with random values

arr2 = np.random.random((3, 3, 3))
print(arr2)

arr3 = np.random.rand(27)
print(arr3)
arr3 = arr3.reshape(3, 3, 3)
print(arr3)

[[[0.22064621 0.47872018 0.15970047]
  [0.55639413 0.06942469 0.80018875]
  [0.64647702 0.24030178 0.23355133]]

 [[0.35067639 0.12760453 0.61660264]
  [0.30762343 0.0728049  0.14968681]
  [0.78542346 0.70308522 0.55277172]]

 [[0.56239501 0.93079443 0.28194152]
  [0.13388306 0.01679979 0.20248863]
  [0.99620258 0.42499686 0.70400207]]]
[0.24735474 0.5173422  0.47559791 0.62343204 0.37668649 0.72278643
 0.35382326 0.49230934 0.71117367 0.34349689 0.43741105 0.16261008
 0.64136639 0.53787619 0.12955945 0.58815844 0.85673945 0.00799241
 0.07889793 0.73865568 0.48504191 0.51891287 0.72913345 0.37323082
 0.17824644 0.74651182 0.746583  ]
[[[0.24735474 0.5173422  0.47559791]
  [0.62343204 0.37668649 0.72278643]
  [0.35382326 0.49230934 0.71117367]]

 [[0.34349689 0.43741105 0.16261008]
  [0.64136639 0.53787619 0.12955945]
  [0.58815844 0.85673945 0.00799241]]

 [[0.07889793 0.73865568 0.48504191]
  [0.51891287 0.72913345 0.37323082]
  [0.17824644 0.74651182 0.746583  ]]]


In [77]:
# Task-13: Create a 10x10 array with random values and find the minimum and maximum values

arr = np.random.random((10, 10))
print(arr)
min_arr, max_arr = arr.min(), arr.max()
print(str(min_arr) + " & " + str(max_arr))
print(min_arr, max_arr)

[[0.68522109 0.41743215 0.90306076 0.60411315 0.03877926 0.5479959
  0.8217681  0.4411219  0.85996966 0.87308692]
 [0.7078543  0.38976615 0.93681645 0.84572537 0.44638141 0.82892229
  0.65342238 0.42644166 0.84458385 0.04724147]
 [0.87911209 0.16036097 0.97402725 0.6992948  0.07939635 0.89893315
  0.03564741 0.34664375 0.0312041  0.37811925]
 [0.63403895 0.13635458 0.48498994 0.33303902 0.96648244 0.45456027
  0.47490745 0.28201971 0.06638063 0.31831535]
 [0.69309353 0.08448497 0.45090492 0.81074499 0.8747237  0.52390332
  0.7670974  0.32969208 0.67706353 0.40116171]
 [0.61459683 0.21682885 0.76875649 0.78847441 0.28873324 0.09188027
  0.48064327 0.3682055  0.44268502 0.46050417]
 [0.62707294 0.58325034 0.5678847  0.37509474 0.79259021 0.03633991
  0.26059318 0.4482628  0.24684267 0.9041349 ]
 [0.50606458 0.50062576 0.56289511 0.94020628 0.91166185 0.19661479
  0.31830121 0.96402088 0.45696901 0.07774987]
 [0.94733919 0.12252312 0.59433817 0.45489574 0.96916876 0.72482165
  0.23190213 

In [81]:
# Task-14: Create a random vector of size 30 and find the mean value

arr = np.random.random(30)
print(arr)
arr.sort()
print(arr)
mean = np.mean(arr)
print(mean) # in 2D or above, the mean of axis can be got 

[0.47747945 0.55201135 0.84763947 0.29538306 0.34096254 0.21818831
 0.75687132 0.85678692 0.85596964 0.59858525 0.06493934 0.58751075
 0.84053039 0.90880526 0.87353739 0.93213327 0.76251945 0.79589293
 0.82567038 0.92354888 0.01484339 0.94230413 0.67193989 0.86627819
 0.31220413 0.32068923 0.49402029 0.95996691 0.82177359 0.77807832]
[0.01484339 0.06493934 0.21818831 0.29538306 0.31220413 0.32068923
 0.34096254 0.47747945 0.49402029 0.55201135 0.58751075 0.59858525
 0.67193989 0.75687132 0.76251945 0.77807832 0.79589293 0.82177359
 0.82567038 0.84053039 0.84763947 0.85596964 0.85678692 0.86627819
 0.87353739 0.90880526 0.92354888 0.93213327 0.94230413 0.95996691]
0.6499021138165635


In [83]:
# Task-15: 15. Create a 2d array with 1 on the border and 0 inside

arr = np.ones((9, 9))
print(arr)
arr[1:-1, 1:-1] = 0;
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
